name: maven

on: 
  push:
    paths-ignore:
    - "docs/**"
    branches:
    - master
    - release/*
  pull_request:
    paths-ignore:
    - "docs/**"
    branches:
    - master  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2    
        
    - name: Build with Maven
      run: mvn clean package --file pom.xml
            
    - name: Run integration test with -Parq-wildfly-managed
      run: mvn clean verify -Parq-wildfly-managed
      
    - name: Run integration test with -Parq-wildfly-embedded
      run: mvn clean verify -Parq-wildfly-embedded
      
    - name: Run integration test with -Parq-glassfish-managed
      run: mvn clean verify -Parq-glassfish-managed    
      
    - name: Run integration test with -Parq-glassfish-embedded
      run: mvn clean verify -Parq-glassfish-embedded   
       
    - name: Run integration test with -Parq-payara-managed
      run: mvn clean verify -Parq-payara-managed
      
    - name: Run integration test with -Parq-payara-embedded
      run: mvn clean verify -Parq-payara-embedded
      
    - name: Run integration test with -Parq-payara-micro
      run: mvn clean verify -Parq-payara-micro
      
    - name: Run integration test with -Parq-liberty-managed
      run: mvn clean verify -Parq-liberty-managed  
